# .github/workflows/push-build.yaml

on:
  push:
    branches:
      - main

jobs:
  build-ubuntu-22_04-amd64:
    name: release linux/amd64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: "Run Go tests"
        shell: bash
        run: |
          go build main.go
