# .github/workflows/push-build.yaml

on: 
  push:
    branches:
      - main

jobs:
  build-ubuntu-20_04-amd64:
    name: release linux/amd64
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: "Run Go tests"
      shell: bash
      run: |
        go build main.go
