# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  release-ubuntu-20_04-amd64:
    name: release linux/amd64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          overwrite: TRUE
          ldflags: "-w -s"
          binary_name: "mysql-ps"
          extra_files: .env.example ReadMe.md
          retry: 10
          asset_name: "mysql-ps-ubuntu-2004-amd64"
  release-ubuntu-22_04-amd64:
    name: release linux/amd64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          overwrite: TRUE
          ldflags: "-w -s"
          binary_name: "mysql-ps"
          extra_files: .env.example ReadMe.md
          retry: 10
          asset_name: "mysql-ps-ubuntu-2204-amd64"
